name: Playwright Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test-version:
    runs-on: ubuntu-latest
    outputs:
      playwright-version: ${{steps.dep-version.outputs.playwright-version}}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      
      - name: Install dependencies
        run: yarn install --immutable

      - name: Find Playwright version
        id: dep-version
        run: |
          echo "playwright-version=$(yarn dep-version @playwright/test)" >> $GITHUB_OUTPUT

  test:
    needs:
      - test-version
    timeout-minutes: 60
    container: mcr.microsoft.com/playwright:v${{needs.test-version.outpus.playwright-version}}-focal
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run Playwright tests
        run: HOME=/root yarn playwright test

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
